services:
  - type: web
    name: prestij25-jn-engine
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER_SERVICE_NAME
        value: prestij25-jn-engine
      - key: DATABASE_URL
        fromDatabase:
          name: prestij25-jn-db
          property: connectionString

databases:
  - name: prestij25-jn-db
    plan: free
